emp_inicio:
    path:     /
    defaults: { _controller: EmpleadoFrontEndBundle:Default:index }
    
logout:
    pattern:   /logout
    
login:
    pattern:   /login
    defaults:  { _controller: EmpleadoFrontEndBundle:Seguridad:login }
    
login_check:
    pattern:   /login_check    
    
emp_usuario_consulta_pago:
    path:     /usuario/consulta/pago
    defaults: { _controller: EmpleadoFrontEndBundle:ConsultaPago:lista }    
