emp_inicio:
    path:     /
    defaults: { _controller: EmpleadoFrontEndBundle:Default:index }
    
logout:
    pattern:   /logout
    
login:
    pattern:   /login
    defaults:  { _controller: EmpleadoFrontEndBundle:Seguridad:login }
    
login_check:
    pattern:   /login_check    

registro:
    pattern:   /registro
    defaults:  { _controller: EmpleadoFrontEndBundle:ProcesoRegistro:nuevo }
    
emp_usuario_consulta_carta_laboral:
    path:     /usuario/consulta/carta/laboral
    defaults: { _controller: EmpleadoFrontEndBundle:ConsultaCartaLaboral:lista }

emp_usuario_consulta_pago:
    path:     /usuario/consulta/pago
    defaults: { _controller: EmpleadoFrontEndBundle:ConsultaPago:lista }
    
emp_usuario_consulta_proceso_disciplinario:
    path:     /usuario/consulta/proceso/disciplinario
    defaults: { _controller: EmpleadoFrontEndBundle:ConsultaProcesoDisciplinario:lista } 
    
emp_usuario_consulta_incapacidad:
    path:     /usuario/consulta/incapacidades
    defaults: { _controller: EmpleadoFrontEndBundle:ConsultaIncapacidades:lista }    

emp_admin_usuario_lista:
    path:     /admin/usuario/lista
    defaults: { _controller: EmpleadoFrontEndBundle:Usuario:lista }

emp_admin_usuario_nuevo:
    path:     /admin/usuario/nuevo/{codigoUsuario}
    defaults: { _controller: EmpleadoFrontEndBundle:Usuario:nuevo } 
    
emp_admin_usuario_editar:
    path:     /admin/usuario/editar/{codigoUsuario}
    defaults: { _controller: EmpleadoFrontEndBundle:Usuario:editar } 
    
emp_usuario_consulta_vacacion:
    path:     /usuario/consulta/vacaciones
    defaults: { _controller: EmpleadoFrontEndBundle:ConsultaVacaciones:lista }     
    
emp_usuario_consulta_prestacion_final:
    path:     /usuario/consulta/prestaciones/finales
    defaults: { _controller: EmpleadoFrontEndBundle:ConsultaPrestaciones:lista }   
    
emp_proceso_clave_cambiar:
    path:     /proceso/clave/cambiar
    defaults: { _controller: EmpleadoFrontEndBundle:ProcesoClave:cambiar }    

emp_proceso_clave_recuperar:
    path:     /proceso/clave/recuperar
    defaults: { _controller: EmpleadoFrontEndBundle:ProcesoClave:recuperar } 