security:
    encoders:
        Empleado\FrontEndBundle\Entity\User:
            algorithm: bcrypt
 
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        
    providers:
        our_db_provider:
            entity:
                class: EmpleadoFrontEndBundle:User
                property: username
 

    firewalls:       
        main:
            pattern: /.*
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
                remember_me: true
            logout:
                path: /logout
                target: /
            remember_me:
                key: MiClaveSegura
                lifetime: 1800
                path: /.*
                domain: ~
            security: true
            anonymous: true
            
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /proceso/clave/recuperar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /usuario, roles: ROLE_USER }
        - { path: /admin, roles: ROLE_ADMIN }
        - { path: /.*, roles: ROLE_USER }        
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }        