<?php

namespace Empleado\FrontEndBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenContenidoFormatoRepository extends EntityRepository {
    
    public function listaDql() {        
        $dql   = "SELECT cf FROM BrasaGeneralBundle:GenContenidoFormato cf WHERE cf.codigoContenidoFormatoPk <> 0";        
        $dql .= " ORDER BY cf.codigoContenidoFormatoPk";
        return $dql;
    }
}