<?php

namespace Empleado\FrontEndBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuDisciplinarioRepository extends EntityRepository {
    
    public function listaDQL($intCodigoEmpleado = "", $intCodigoProcesoDisciplinario = 0) {        
        $dql   = "SELECT d FROM EmpleadoFrontEndBundle:RhuDisciplinario d WHERE d.codigoEmpleadoFk = " . $intCodigoEmpleado;
        if($intCodigoProcesoDisciplinario != "" && $intCodigoProcesoDisciplinario != 0) {
            $dql .= " AND d.codigoDisciplinarioPk = " . $intCodigoProcesoDisciplinario;
        }
        $dql .= " ORDER BY d.codigoDisciplinarioPk DESC";
        return $dql;
    }
     
}