<?php

namespace Empleado\FrontEndBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhuLiquidacionRepository extends EntityRepository {
    
    public function listaDQL($intCodigoEmpleado = "", $intCodigoLiquidacion = 0) {        
        $dql   = "SELECT l FROM EmpleadoFrontEndBundle:RhuLiquidacion l WHERE l.codigoEmpleadoFk = " . $intCodigoEmpleado;
        if($intCodigoLiquidacion != "" && $intCodigoLiquidacion != 0) {
            $dql .= " AND l.codigoLiquidacionPk = " . $intCodigoLiquidacion;
        }
        $dql .= " ORDER BY l.codigoLiquidacionPk DESC";
        return $dql;
    } 
    
    
}